Repository crawling-project-crowrong/it-cast, pull requests merged in 2025-01, with the labels that each got.

#90 deploy: CI/CD Test
  .github/workflows/itcast-build-and-deploy.yml
  .github/workflows/itcast-build-and-test.yml
  admin/src/main/resources/application-prod.yml
  appspec.yml
  b2c/src/main/resources/application-prod.yml
  common/src/main/resources/application-prod.yml
  schedule/src/main/java/itcast/Test.java
  schedule/src/main/java/itcast/blog/parser/YozmDataParser.java
  schedule/src/main/resources/application-prod.yml
  schedule/src/test/java/itcast/blog/application/YozmCrawlingServiceTest.java
  scripts/deploy.sh
Labels: 🌐deploy

#102 refactor: 뉴스 관련 코드 최적화
  admin/src/test/java/itcast/AdminNewsServiceTest.java
  common/src/main/java/itcast/exception/ErrorCodes.java
  schedule/src/main/java/itcast/ai/dto/request/GPTSummaryRequest.java
  schedule/src/main/java/itcast/news/application/NewsService.java
  schedule/src/main/java/itcast/news/application/SendNewsService.java
  schedule/src/test/java/itcast/news/application/NewsServiceTest.java
  schedule/src/test/java/itcast/news/application/SelectNewsServiceTest.java
Labels: 🧾docs

#104 refactor: 메일 발송 로직이 비동기로 돌아가게 변경
  common/src/main/java/itcast/async/AsyncConfig.java
  schedule/src/main/java/itcast/mail/application/MailService.java
Labels: 🔧refactor

#107 feat: 관리자 뉴스 히스토리 조회
  admin/src/main/java/itcast/application/AdminNewsHistoryService.java
  admin/src/main/java/itcast/application/AdminNewsService.java
  admin/src/main/java/itcast/controller/AdminNewsHistoryController.java
  admin/src/main/java/itcast/dto/response/AdminNewsHistoryResponse.java
  admin/src/main/java/itcast/repository/CustomNewsHistoryRepository.java
  admin/src/main/java/itcast/repository/CustomNewsHistoryRepositoryImpl.java
  admin/src/main/java/itcast/repository/NewsHistoryRepository.java
  admin/src/test/java/itcast/AdminNewsHistoryServiceTest.java
  common/src/main/java/itcast/domain/newsHistory/NewsHistory.java
Labels: 🧑‍💻feature

#109 feat: 관리자 블로그 히스토리 조회
  admin/src/main/java/itcast/application/AdminBlogHistoryService.java
  admin/src/main/java/itcast/controller/AdminBlogHistoryController.java
  admin/src/main/java/itcast/dto/response/AdminBlogHistoryResponse.java
  admin/src/main/java/itcast/repository/BlogHistoryRepository.java
  admin/src/main/java/itcast/repository/CustomBlogHistoryRepository.java
  admin/src/main/java/itcast/repository/CustomBlogHistoryRepositoryImpl.java
  admin/src/test/java/itcast/AdminBlogHistoryServiceTest.java
  common/src/main/java/itcast/domain/blogHistory/BlogHistory.java
Labels: 🧑‍💻feature

#106 refactor: 이메일 템플릿 수정 및 프롬프트 수정
  schedule/src/main/resources/application.yml
  schedule/src/main/resources/templates/email-template.html
  schedule/src/test/java/itcast/mail/application/MailIntegrationServiceTest.java
Labels: 🔧refactor

#112 refactor: 히스토리 테스트 Mock으로 변경
  admin/src/test/java/itcast/AdminBlogHistoryServiceTest.java
  admin/src/test/java/itcast/AdminNewsHistoryServiceTest.java
  admin/src/test/java/itcast/AdminNewsServiceTest.java
  common/src/main/java/itcast/domain/newsHistory/NewsHistory.java
Labels: 🔧refactor

#117 feat: 뉴스 히스토리 CSV 파일 다운로드 기능 구현
  admin/build.gradle
  admin/src/main/java/itcast/application/AdminNewsHistoryService.java
  admin/src/main/java/itcast/controller/AdminNewsHistoryController.java
  admin/src/main/java/itcast/repository/CustomNewsHistoryRepository.java
  admin/src/main/java/itcast/repository/CustomNewsHistoryRepositoryImpl.java
  admin/src/test/java/itcast/AdminNewsHistoryServiceTest.java
  common/src/main/java/itcast/domain/newsHistory/NewsHistory.java
Labels: 🧑‍💻feature

#119 feat: 블로그 히스토리 CSV 파일 다운로드 기능 구현
  admin/src/main/java/itcast/application/AdminBlogHistoryService.java
  admin/src/main/java/itcast/controller/AdminBlogHistoryController.java
  admin/src/main/java/itcast/repository/CustomBlogHistoryRepository.java
  admin/src/main/java/itcast/repository/CustomBlogHistoryRepositoryImpl.java
  admin/src/test/java/itcast/AdminBlogHistoryServiceTest.java
  schedule/src/main/java/itcast/news/application/NewsService.java
Labels: 🧑‍💻feature

#127 feat: 관리자 메일 조회 구현
  admin/src/main/java/itcast/application/AdminCheckService.java
  admin/src/main/java/itcast/application/AdminMailService.java
  admin/src/main/java/itcast/controller/AdminMailController.java
  admin/src/main/java/itcast/dto/response/MailResponse.java
  admin/src/main/resources/templates/email-template.html
  admin/src/test/java/itcast/AdminMailServiceTest.java
Labels: 🧑‍💻feature

#135 deploy: 배포 작업 마무리(log쪽 에러 해결)
  .github/workflows/itcast-build-and-deploy.yml
  admin/src/main/java/itcast/controller/AdminBlogController.java
  admin/src/main/java/itcast/controller/AdminBlogHistoryController.java
  admin/src/main/java/itcast/logging/logs/error/error.log
  admin/src/main/java/itcast/logging/logs/info/info.log
  admin/src/main/java/itcast/logging/logs/warn/warn.log
  admin/src/main/resources/application-prod.yml
  admin/src/main/resources/logback-spring.xml
  b2c/src/main/resources/application-prod.yml
  b2c/src/main/resources/logback-spring.xml
  b2c/src/main/resources/static/index.html
  build.gradle
  schedule/src/main/java/itcast/Test.java
  schedule/src/main/java/itcast/blog/application/TestController.java
  schedule/src/main/resources/application-prod.yml
  schedule/src/main/resources/logback-spring.xml
  schedule/src/test/java/itcast/mail/application/MailIntegrationServiceTest.java
Labels: 🌐deploy

#121 feat: 뉴스 히스토리 CSV 파일 메일 발송 구현
  admin/build.gradle
  admin/src/main/java/itcast/application/AdminNewsHistoryService.java
  admin/src/main/java/itcast/config/MailConfig.java
  admin/src/main/java/itcast/controller/AdminNewsHistoryController.java
  admin/src/main/java/itcast/dto/request/MailProperties.java
  admin/src/main/resources/application-prod.yml
  admin/src/main/resources/application.yml
  admin/src/test/java/itcast/AdminNewsHistoryServiceTest.java
Labels: 🧑‍💻feature

#123 feat: 블로그 히스토리 CSV 파일 메일 발송 구현
  admin/src/main/java/itcast/application/AdminBlogHistoryService.java
  admin/src/main/java/itcast/controller/AdminBlogHistoryController.java
  admin/src/main/java/itcast/dto/request/MailProperties.java
  admin/src/test/java/itcast/AdminBlogHistoryServiceTest.java
Labels: 🧑‍💻feature

#133 feat: 관리자 실패 메일 재 발송
  admin/build.gradle
  admin/src/main/java/itcast/application/AdminEmailSender.java
  admin/src/main/java/itcast/application/AdminMailService.java
  admin/src/main/java/itcast/controller/AdminMailController.java
  admin/src/main/java/itcast/dto/request/AdminSendMailRequest.java
  common/src/main/java/itcast/exception/ErrorCodes.java
  common/src/main/java/itcast/jwt/repository/UserRepository.java
  common/src/main/java/itcast/mail/repository/MailEventsRepository.java
Labels: 🧑‍💻feature
